### ISSUE TITLE
Documentation for the last version of edX

### ISSUE THREAD

**Issue by andricicezar** [Denis1990/sshxblock#10]
Hello guys,

I know that this repository wasn't updated for a while, but I really want to try this XBlock this weekend. If you can help me I will appreciate it very much.

I tried to install your XBlock with the following tutorial: https://github.com/edx/edx-platform/wiki/Installing-a-new-XBlock, but it didn't work. Plus, looks like is obsolete.

Can you help me please?

Thank you,
Cezar

**Comment by mirobillis** [comment]
Hello!
Yes this project is kinda abandoned it was for a seminar we attended.
I would be happy to help but i will be away for some months with neither internet nor computer.Have you tried to install another xblock or the problem occurs only with this one?
You can post specific errors and maybe dennis can help if he will be available.
I tried it some months ago on localhost on an virtual enviroment and it worked fine

These were the directions we followed to make it work from setting the virtual enviroment to creating and testing the xblock.They are in greek but maybe you can just translate with google and find something usefull.--> https://github.com/maellak/edx-seminar or search in the official repository here https://github.com/edx/XBlock the readme

Have you tried to clean your database?I had this problem when i tried to add new Xblock and fixed it with  commands like these
sudo rm /edx/var/mongo/mongodb/mongod.lock
sudo -u mongodb mongod --dbpath /edx/var/mongo/mongodb --repair --repairpath /edx/var/mongo/mongodb
sudo start mongod

and after this
sudo -u edxapp 
/edx/bin/pip.edxapp install /path/to/your/block
or with install --upgrade

Sorry for the incocience.I hope i helped you
Regards,
Βασίλης(Greek) -Bill

**Comment by andricicezar** [comment]
Thank you for the fast response!

I have tried what you have said, but a lot of things didn't match and I couldn't figure it out.

I found a different solution: use an iframe + this tool. http://xmodulo.com/access-ssh-terminal-web-browser-linux.html. Works like a charm.

Thank you again for the fast response!

Best regards,
Cezar
